Importar Librerias

In [1]:
import pandas as pd
import numpy as np

Conexion a PostgreSQL

In [2]:
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 27.8 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

In [3]:
from sqlalchemy import create_engine
#En esta url va nuestra base de datos (En este caso en render)
database_url = "postgresql://etl_seguros_fwgm_user:FLIwCR2BnSl9vmgdqKd7GtpzOyBHRpyl@dpg-d6qu5hk50q8c73bpe0p0-a.oregon-postgres.render.com/etl_seguros_fwgm"
engine = create_engine(database_url)

Cargar Dataset

In [46]:
#En esta url va el RAW de nuestro csv subido en github
url = "https://raw.githubusercontent.com/MendezBy02/etl-data-pipeline-25-1449-2022/refs/heads/main/data/raw/B_productos.csv"
productos = pd.read_csv(url)

Exploración de datos

In [47]:
productos.head()

  id_producto       producto  precio id_proveedor
0      PR1000       Router 0  625.11         P325
1      PR1001      Teclado 1   61.12          NaN
2      PR1002        Mouse 2  203.71         P305
3      PR1003      Teclado 3  886.95         P304
4      PR1004   Impresora 4   103.94         P304

In [48]:
productos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 146 entries, 0 to 145
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_producto   146 non-null    object
 1   producto      146 non-null    object
 2   precio        139 non-null    object
 3   id_proveedor  137 non-null    object
dtypes: object(4)
memory usage: 4.7+ KB

In [49]:
productos.isnull().sum()

id_producto     0
producto        0
precio          7
id_proveedor    9
dtype: int64

In [54]:
productos.duplicated().sum()

np.int64(0)

Funciones reutilizables

In [51]:
#Normalizar columnas

def normalizar_columnas(df):
  df.columns =(
      df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ","_")
  )
  return df

In [52]:
#Limpiar texto

def limpiar_texto(df):

  for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].astype(str).str.strip()

    df[col] = df[col].replace(
        ["nan","None","Null","null",""],
        pd.NA
        )
    return df

Aplicar Limpieza

In [53]:
productos = normalizar_columnas(productos)
productos = limpiar_texto(productos)
productos = productos.drop_duplicates()

Funciones especificas

In [60]:
#Limpiar el precio y convertirlo a float

productos["precio"] = (
    productos["precio"]
    .astype(str)
    .str.extract(r'(\d+\.?\d*)'))[0].astype(float)

In [61]:
productos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 140 entries, 0 to 139
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_producto   140 non-null    object
 1   producto      140 non-null    object
 2   precio        133 non-null    float64
 3   id_proveedor  133 non-null    object
dtypes: float64(1), object(3)
memory usage: 5.5+ KB

In [59]:
productos.head()

  id_producto       producto  precio id_proveedor
0      PR1000       Router 0  625.11         P325
1      PR1001      Teclado 1   61.12          NaN
2      PR1002        Mouse 2  203.71         P305
3      PR1003      Teclado 3  886.95         P304
4      PR1004   Impresora 4   103.94         P304

Separar validos y rechazados

In [64]:
#Primero debemos colocar que reglas queremos tener para poder separarlos entra validos y rechazados
#Reglas
#1. Los tipo ID's deben ser not null
#2. El stock y la bodega no pueden estar vacios y stock no puede ser negativo

columnas_obligatorias = [
    "id_producto",
    "id_proveedor",
    "precio",
    "producto"
]

condicion_nulos = productos[columnas_obligatorias].isna().any(axis=1)

condicion_precio_invalido = productos["precio"] <= 0

condicion_rechazo = condicion_nulos | condicion_precio_invalido

rechazados = productos.loc[condicion_rechazo].copy()
validos = productos.loc[~condicion_rechazo].copy()

Motivo del rechazo

In [67]:
from pandas.core.dtypes.missing import isna
def motivo(row):

  motivos = []

  if pd.isna(row["id_producto"]):
    motivos.append("ID_productos_no_valido")

  if pd.isna(row["id_proveedor"]):
    motivos.append("ID_proveedor_no_valido")

  if pd.isna(row["precio"]):
    motivos.append("precio_no_valido")

  if pd.isna(row["producto"]):
    motivos.append("producto_no_valido")

  elif row["precio"] < 0:
      motivos.append("precio_no_puede_ser_negativo")

  return ",".join(motivos)

Agregar motivo de rechazo

In [68]:
rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

Exportar Archivos

In [69]:
validos.to_csv("productos_curated.csv", index=False)
rechazados.to_csv("productos_rejects.csv", index=False)

Cargar datos en PostgreSQL

Para evitar errores de carga y mostrar los detalles

In [70]:
validos.head()

  id_producto       producto  precio id_proveedor
0      PR1000       Router 0  625.11         P325
2      PR1002        Mouse 2  203.71         P305
3      PR1003      Teclado 3  886.95         P304
4      PR1004   Impresora 4   103.94         P304
5      PR1005       Router 5  725.77         P322

In [71]:
validos.dtypes

id_producto      object
producto         object
precio          float64
id_proveedor     object
dtype: object

In [72]:
validos.isnull().sum()

id_producto     0
producto        0
precio          0
id_proveedor    0
dtype: int64

In [73]:
productos.value_counts()

id_producto  producto        precio   id_proveedor
PR1000       Router 0        625.11   P325            1
PR1002       Mouse 2         203.71   P305            1
PR1003       Teclado 3       886.95   P304            1
PR1004        Impresora 4    103.94   P304            1
PR1005       Router 5        725.77   P322            1
                                                     ..
PR1134       Escritorio 134  1131.56  P334            1
PR1136       Teclado 136     731.25   P314            1
PR1137       Audífonos 137   617.66   P328            1
PR1138       Webcam 138      280.65   P328            1
PR1139       Laptop 139      215.95   P310            1
Name: count, Length: 126, dtype: int64

In [74]:
validos.to_sql(
    "productos",
    engine,
    if_exists="append",
    index=False
  )

126

Validar Carga

In [75]:
pd.read_sql(
    "Select * From productos Limit 100",
    engine
)

   id_producto       producto  precio id_proveedor
0       PR1000       Router 0  625.11         P325
1       PR1002        Mouse 2  203.71         P305
2       PR1003      Teclado 3  886.95         P304
3       PR1004   Impresora 4   103.94         P304
4       PR1005       Router 5  725.77         P322
..         ...            ...     ...          ...
95      PR1107  Proyector 107  504.23         P321
96      PR1108     Tablet 108  508.52         P316
97      PR1109     Router 109  886.41         P309
98      PR1110     Router 110  290.34         P300
99      PR1111    Webcam 111   137.02         P321

[100 rows x 4 columns]