Importar Librerias

In [1]:
import pandas as pd
import numpy as np

Conexion a PostgreSQL

In [2]:
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 27.8 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

In [3]:
from sqlalchemy import create_engine
#En esta url va nuestra base de datos (En este caso en render)
database_url = "postgresql://etl_seguros_fwgm_user:FLIwCR2BnSl9vmgdqKd7GtpzOyBHRpyl@dpg-d6qu5hk50q8c73bpe0p0-a.oregon-postgres.render.com/etl_seguros_fwgm"
engine = create_engine(database_url)

Cargar Dataset

In [5]:
#En esta url va el RAW de nuestro csv subido en github
url = "https://raw.githubusercontent.com/MendezBy02/etl-data-pipeline-25-1449-2022/refs/heads/main/data/raw/B_inventario.csv"
inventario = pd.read_csv(url)

Exploración de datos

In [6]:
inventario.head()

  id_inventario id_producto stock      bodega
0         I7000      PR1115   165    Tránsito
1         I7001      PR1031   236  Sucursal 1
2         I7002      PR1129    40  Sucursal 2
3         I7003      PR1083    61     Central
4         I7004      PR1021   245     Central

In [7]:
inventario.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 186 entries, 0 to 185
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_inventario  186 non-null    object
 1   id_producto    180 non-null    object
 2   stock          181 non-null    object
 3   bodega         186 non-null    object
dtypes: object(4)
memory usage: 5.9+ KB

In [21]:
inventario.isnull().sum()

id_inventario    0
id_producto      6
stock            0
bodega           0
dtype: int64

In [18]:
inventario.duplicated().sum()

np.int64(0)

Funciones reutilizables

In [12]:
#Normalizar columnas

def normalizar_columnas(df):
  df.columns =(
      df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ","_")
  )
  return df

In [13]:
#Limpiar texto

def limpiar_texto(df):

  for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].astype(str).str.strip()

    df[col] = df[col].replace(
        ["nan","None","Null","null",""],
        pd.NA
        )
    return df

Aplicar Limpieza

In [14]:
inventario = normalizar_columnas(inventario)
inventario = limpiar_texto(inventario)
inventario = inventario.drop_duplicates()

Funciones especificas

In [20]:
#Normalización de bodega

map_bodega = {
    "Transito": "Tránsito",
    "TRANSITO": "Tránsito",

    "CENTRAL": "Central",
    "central": "Central",

    "SUCURSAL 1": "Sucursal 1",
    "sucursal 1": "Sucursal 1",
    "sucursal1" : "Sucursal 1",
    "SUCURSAL1": "Sucursal 1",

    "SUCURSAL 2": "Sucursal 2",
    "sucursal 2": "Sucursal 2",
    "sucursal2" : "Sucursal 2",
    "SUCURSAL2": "Sucursal 2"
}

inventario["bodega"] = (
    inventario["bodega"]
    .astype(str)
    .str.strip()
    .replace(map_bodega)
)

#Limpiar texto

inventario["stock"] = inventario["stock"].astype(str).str.replace("R/D", "", regex=True)

#Convertir a entero

inventario["stock"] = pd.to_numeric(inventario["stock"], errors="coerce")

#Manejar nulos

inventario["stock"] = inventario["stock"].fillna(0).astype(int)

In [22]:
inventario.info()

<class 'pandas.core.frame.DataFrame'>
Index: 180 entries, 0 to 179
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_inventario  180 non-null    object
 1   id_producto    174 non-null    object
 2   stock          180 non-null    int64
 3   bodega         180 non-null    object
dtypes: int64(1), object(3)
memory usage: 7.0+ KB

In [23]:
inventario.head()

  id_inventario id_producto  stock      bodega
0         I7000      PR1115    165    Tránsito
1         I7001      PR1031    236  Sucursal 1
2         I7002      PR1129     40  Sucursal 2
3         I7003      PR1083     61     Central
4         I7004      PR1021    245     Central

Separar validos y rechazados

In [34]:
#Primero debemos colocar que reglas queremos tener para poder separarlos entra validos y rechazados
#Reglas
#1. Los tipo ID's deben ser not null
#2. El stock y la bodega no pueden estar vacios y stock no puede ser negativo

columnas_obligatorias = [
    "id_inventario",
    "id_producto",
    "stock",
    "bodega"
]

condicion_nulos = inventario[columnas_obligatorias].isna().any(axis=1)

condicion_stock_invalido = inventario["stock"] < 0

condicion_rechazo = condicion_nulos | condicion_stock_invalido

rechazados = inventario.loc[condicion_rechazo].copy()
validos = inventario.loc[~condicion_rechazo].copy()

Motivo del rechazo

In [35]:
from pandas.core.dtypes.missing import isna
def motivo(row):

  motivos = []

  if pd.isna(row["id_inventario"]):
    motivos.append("ID_inventario_no_valido")

  if pd.isna(row["id_producto"]):
    motivos.append("ID_producto_no_valido")

  if pd.isna(row["stock"]):
    motivos.append("stock_invalido")

  if pd.isna(row["bodega"]):
    motivos.append("bodega_invalida")

  elif row["stock"] < 0:
      motivos.append("stock_no_puede_ser_negativo")

  return ",".join(motivos)

Agregar motivo de rechazo

In [36]:
rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

Exportar Archivos

In [37]:
validos.to_csv("inventario_curated.csv", index=False)
rechazados.to_csv("inventario_rejects.csv", index=False)

Cargar datos en PostgreSQL

Para evitar errores de carga y mostrar los detalles

In [38]:
validos.head()

  id_inventario id_producto  stock      bodega
0         I7000      PR1115    165    Tránsito
1         I7001      PR1031    236  Sucursal 1
2         I7002      PR1129     40  Sucursal 2
3         I7003      PR1083     61     Central
4         I7004      PR1021    245     Central

In [39]:
validos.dtypes

id_inventario    object
id_producto      object
stock             int64
bodega           object
dtype: object

In [40]:
validos.isnull().sum()

id_inventario    0
id_producto      0
stock            0
bodega           0
dtype: int64

In [41]:
inventario.value_counts()

id_inventario  id_producto  stock  bodega
I7000          PR1115       165    Tránsito      1
I7001          PR1031       236    Sucursal 1    1
I7002          PR1129       40     Sucursal 2    1
I7003          PR1083       61     Central       1
I7004          PR1021       245    Central       1
                                                ..
I7175          PR1077       89     Sucursal 1    1
I7176          PR1001       0      Central       1
I7177          PR1118       219    Sucursal 1    1
I7178          PR1036       193    Tránsito      1
I7179          PR1068       241    Central       1
Name: count, Length: 174, dtype: int64

In [42]:
validos.to_sql(
    "inventario",
    engine,
    if_exists="append",
    index=False
  )

174

Validar Carga

In [43]:
pd.read_sql(
    "Select * From inventario Limit 100",
    engine
)

   id_inventario id_producto  stock      bodega
0          I7000      PR1115    165    Tránsito
1          I7001      PR1031    236  Sucursal 1
2          I7002      PR1129     40  Sucursal 2
3          I7003      PR1083     61     Central
4          I7004      PR1021    245     Central
..           ...         ...    ...         ...
95         I7096      PR1040    205  Sucursal 2
96         I7097      PR1113     11     Central
97         I7098      PR1007    233     Central
98         I7099      PR1071     19  Sucursal 2
99         I7100      PR1091    180  Sucursal 2

[100 rows x 4 columns]